apiVersion: v1
kind: ReplicationController
metadata:
  name: alpine
spec:
  replicas: 4
  selector:
    app: alpine-box
  template:
    metadata:
      name: alpine
      labels:
        app: alpine-box
    spec:
      containers:
      - name: nginx-box
        image: nginx
        command: ["sleep", "3600"]
